### PR TITLE
Webpack support

### PR DESCRIPTION
**Pull request by flobacher**
Hi and thank you for your awesome example!

I added support for webpack. Please check it.
I had some problems with jest, but they existed even before I did my changes.. somehow it seems to me, that esm syntax does not get transpiled to commonjs and then jest chokes on the `import` statements.

Thank you =)

### CODE REVIEW

**Comment by damassi** [comment]
Hi @flobacher - I'm just getting back from vacation but will give this a look over the next few days!

**Comment by damassi** [comment]
@flobacher - Ok, back from vacation and I had an opportunity to give your PR a good look -- thanks so much for your work on this 😄 

The reason why this repo came into being was I wanted to provide a supporting example for a [recent blogpost](http://artsy.github.io/blog/2017/11/27/Babel-7-and-TypeScript/) that was written over at our engineering blog. The idea was to teach, and to take a bare-bones approach in order to tease out common edge-cases, as well as provide a simple, hackable way for others to begin developing their own starter-project templates. Seeing that you were able to dive in and add Webpack without much effort it seems we succeeded! 

That said, I hesitate to merge this because I feel like it would distract from the blogpost while also making it more difficult for absolute beginners to understand whats going on. I'm a big fan of Webpack, and we use it all over Artsy's codebases, but I would say that Webpack is something of an advanced topic that requires some time to understand and grok and can often be intimidating. 

@alloy -- do you have any thoughts?

**Comment by alloy** [comment]
Awesome, thanks for sharing @flobacher :clap:

I agree with @damassi that for the original purpose (to expand on a blog post) adding webpack lowers the ease of understanding the parts covered in the blog post, so I wonder what alternatives are? Maybe the repo could have several distinct examples? i.e. move the current code into `./babel-7-typescript` and the new code into `./babel-7-typescript-webpack`? Or maybe link to this PR from the README?

**Comment by damassi** [comment]
Great idea to move it into an examples folder. That way this repo could serve two purposes -- exploration and education, as well as a solid starting point for a real webapp. If we went that route I'd likely add an example that uses [Parcel](https://parceljs.org) (when i get some time) since I recently saw that there's a new [`parcel-typescript`](https://github.com/fathyb/parcel-plugin-typescript) plugin available.

**Comment by alloy** [comment]
Sounds great 👍

**Comment by flobacher** [comment]
@damassi I actually found your repo because of this awesome blogpost! Thx for that! Feel free to just put a link in the readme to my fork =)

**Comment by damassi** [comment]
@flobacher - will do 👍

**Comment by flobacher** [comment]
@damassi - great! Thx 🙂

**Comment by damassi** [comment]
Updated. Let me know if you end up merging your fork into master and I'll make sure to update the README link

**Pull request closed without merging**
